### ISSUE TITLE
Welcome Screen 1

### ISSUE THREAD

**Issue by RegOpz** [RegOpz/RegOpzWebApp#4]
This is the image of the welcome screen1.
![welcome_screen1](https://cloud.githubusercontent.com/assets/25818407/23470665/fe400f8e-fee1-11e6-9bf4-77b4aa68c195.jpg)

**Comment by daveai** [comment]
issue/4

**Comment by daverbj** [comment]
http://ec2-52-221-7-223.ap-southeast-1.compute.amazonaws.com:8080/#/dashboard
