### ISSUE TITLE
View data Enhancements

### ISSUE THREAD

**Issue by RegOpz** [RegOpz/RegOpzWebApp#86]
+ HOC for access of the module
>>>>>>> View Data grid
+ HOC to be applied similar to maintain business rules
+ View data grid button Change History for the data should : 
           a) History modal should have date range search for focused search/filter of the data
           b) History modal should have pages scrolling option
           c) History modal should be searchable for items/column name etc in the reference section
+ View data maker should be allowed to change /amend his own changes. First he needs to reverse the changes from work-flow management, then re-edit the record in concern.
+ View Data grid insert, duplicate, edit, delete buttons should work (remember that we'll not have "id" as  auto_increment column in source data table, so need to handle rowId return properly in API)
+ Insert and Edit of the record should create a dynamic form for editing or inserting data. This will be a dynamic form as the database object structure will be different for different sources.
+ breadcrumb should show "source name" and "business date" for the data grid view. Otherwise need to have the title displaying which source and business date data is being displayed.

**Comment by suchibrata** [comment]
All changes done except for History related changes.
